# Generated by Django 3.1.7 on 2021-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count_of_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
