# Generated by Django 3.1.11 on 2021-06-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210413_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelparticipant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.trip', verbose_name='Поездка'),
        ),
    ]
